# Generated by Django 3.0 on 2019-12-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopCollegesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.CharField(max_length=300)),
                ('college_name', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
                ('score', models.FloatField()),
                ('crank', models.IntegerField()),
            ],
            options={
                'db_table': 'IndiaTop200College2019',
            },
        ),
    ]
