# Generated by Django 3.0 on 2019-12-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayCollegesInMaharashtraModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_code', models.IntegerField()),
                ('course_name', models.CharField(max_length=300)),
                ('shift', models.IntegerField()),
                ('seat_intake', models.IntegerField()),
                ('college_name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'CollegeInMaharashtra2019',
            },
        ),
    ]
