# Generated by Django 3.0 on 2019-12-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllIndiaColleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allindiacollegemodel',
            name='city',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='allindiacollegemodel',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='allindiacollegemodel',
            name='state',
            field=models.CharField(max_length=300),
        ),
    ]
