# Generated by Django 3.0 on 2019-12-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhereAdmissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=300)),
                ('branch', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=300)),
                ('seat_type', models.CharField(max_length=300)),
                ('min_percentage', models.FloatField()),
            ],
            options={
                'db_table': 'CollegeRange2019',
            },
        ),
    ]
